# Generated by Django 5.0.1 on 2024-12-03 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('property_status', models.CharField(max_length=10)),
                ('property_type', models.CharField(max_length=10)),
                ('lux_type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('area', models.PositiveIntegerField()),
                ('price', models.IntegerField()),
                ('beds', models.PositiveIntegerField()),
                ('baths', models.PositiveIntegerField()),
                ('floor', models.CharField(max_length=12)),
                ('elevator', models.CharField(max_length=5)),
                ('parking', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profile_image', models.ImageField(default='static/default_images/blank-profile-picture.webp', upload_to='profile_image')),
                ('phone_number', models.CharField(max_length=15)),
                ('Bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='listing_images')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.listing')),
            ],
        ),
    ]
